name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Gather build info
      run: |
        touch build-info.txt
        git rev-parse --short "$GITHUB_SHA" >> build_info.txt
